# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WinfsInjector < Formula
  desc ""
  homepage ""
  version "0.32.0"

  on_macos do
    url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.32.0/winfs-injector-darwin.tar.gz"
    sha256 "098104430d5a905bfb9e00f10a4890508d77887e4aff42b29e8c53a0334f489a"

    define_method(:install) do
      bin.install "winfs-injector"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the WinfsInjector
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.32.0/winfs-injector-linux.tar.gz"
      sha256 "e4fe737c3fc165de6e24fb6fb140a274799cd33d25387047f18d840be55f129f"
      define_method(:install) do
        bin.install "winfs-injector"
      end
    end
  end

  test do
    system "#{bin}/winfs-injector --version"
  end
end
