# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WinfsInjector < Formula
  desc ""
  homepage ""
  version "0.22.0"

  on_macos do
    url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.22.0/winfs-injector-darwin.tar.gz"
    sha256 "9a79164df9dd5d8ccb95d6dfb34f8a4ce0f84c9a49bd87a37c7ebf6abe931bbe"

    def install
      bin.install "winfs-injector"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the WinfsInjector
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.22.0/winfs-injector-linux.tar.gz"
      sha256 "e1731c00c1413b361c2ca1733ae038ca285469226a7412989da83876db10b28f"

      def install
        bin.install "winfs-injector"
      end
    end
  end

  test do
    system "#{bin}/winfs-injector --version"
  end
end
