# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WinfsInjector < Formula
  desc ""
  homepage ""
  version "0.23.0"

  on_macos do
    url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.23.0/winfs-injector-darwin.tar.gz"
    sha256 "c8af5deb3458cedb688281145c77b4465576ac01479095b3ec1e486852c5cbbe"

    def install
      bin.install "winfs-injector"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the WinfsInjector
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.23.0/winfs-injector-linux.tar.gz"
      sha256 "10358c89e49a5c77a67bfb26cabccafb34c31a6635007c0d7f25da95ec45f665"

      def install
        bin.install "winfs-injector"
      end
    end
  end

  test do
    system "#{bin}/winfs-injector --version"
  end
end
