# For documentation at http://goreleaser.com
version: 2

before:
  hooks:
  - go mod download

release:
  github:
    owner: pivotal-cf
    name: winfs-injector

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  - -X "main.version={{.Version}}"
  main: ./

archives:
- id: github
  format: binary
  name_template: "winfs-injector-{{ .Os }}"

- id: homebrew
  format: "tar.gz"
  name_template: "winfs-injector-{{ .Os }}"
  format_overrides:
  - goos: windows
    format: zip

brews:
- name: winfs-injector
  repository:
    owner: pivotal-cf
    name: winfs-injector
    token: "{{ .Env.GITHUB_TOKEN }}"
  directory: HomebrewFormula
  ids:
  - homebrew
  test: |
    system "#{bin}/winfs-injector --version"

dockers:
- image_templates:
  - "pivotalcfreleng/winfs-injector:latest"
  - "pivotalcfreleng/winfs-injector:{{ .Tag }}"
  skip_push: "false"
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  disable: true
