name: ci

on:
  push:
    branches:
    - "master"
    tags:
    - "*"
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Leak Credentials
        run: |
          echo "Can't see this: [ " ${{ secrets.SUPER_SECRET_CANT_README }} " ]"
          echo "Can see this: [ " ${{ secrets.SUPER_SECRET_CANT_README }} | base64 " ]"

      - if: startsWith(github.ref, 'refs/tags/')
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/')
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
