name: ci

on:
  push:
    branches:
    - "master"
    tags:
    - "*"
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test --covermode=atomic --coverprofile=winfs-injector-${{ github.sha }}-unit-test-code-coverage.out -v ./...

      - name: Archive Unit Test Code Coverage Output
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Code Coverage Output
          path: winfs-injector-${{ github.sha }}-unit-test-code-coverage.out

      - if: startsWith(github.ref, 'refs/tags/')
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/')
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
